[package]
name = "password_generator-backend"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.0"
actix-web = "4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
env_logger = "0.9"
tracing-actix-web = "0.7"
tracing = "0.1"
log = "0.4"